export const SHOW_FEATURES_IN_DEVELOPMENT = false

export const SHOW_STREAM_EDITOR = SHOW_FEATURES_IN_DEVELOPMENT
export const SHOW_REFINED_PAGE = SHOW_FEATURES_IN_DEVELOPMENT
export const SHOW_SETTINGS_PAGE = SHOW_FEATURES_IN_DEVELOPMENT
export const SHOW_STREAM_BACKGROUNDS_IN_DEVELOPMENT = SHOW_FEATURES_IN_DEVELOPMENT
export const SHOW_STREAM_LAYOUTS_WITH_GAMELOG_DATA = SHOW_FEATURES_IN_DEVELOPMENT
export const ENABLE_INVENTORY_SHEET_CALLS = SHOW_FEATURES_IN_DEVELOPMENT
export const SHOW_ACTION_LINK = SHOW_FEATURES_IN_DEVELOPMENT

export const ENABLE_BUDGET_FEATURE = SHOW_FEATURES_IN_DEVELOPMENT && false
export const SHOW_BUDGET_IN_CRAFT = ENABLE_BUDGET_FEATURE
export const SHOW_BUDGET_PAGE = ENABLE_BUDGET_FEATURE
export const ENABLE_BUDGET_SHEET_CALLS = ENABLE_BUDGET_FEATURE

export const CLEAR_WEB_ON_LOAD = false
