export const SHOW_FEATURES_IN_DEVELOPMENT = false

export const SHOW_TT_SERVICE = SHOW_FEATURES_IN_DEVELOPMENT
export const SHOW_STREAM_EDITOR = SHOW_FEATURES_IN_DEVELOPMENT
export const SHOW_REFINED_PAGE = SHOW_FEATURES_IN_DEVELOPMENT

export const SHOW_BUDGET_IN_CRAFT = false
export const SHOW_SHEET_SETTINGS = SHOW_BUDGET_IN_CRAFT || SHOW_TT_SERVICE
export const SHOW_BUDGET_PAGE = SHOW_BUDGET_IN_CRAFT
export const SHOW_SETTINGS_PAGE = SHOW_SHEET_SETTINGS

export const CLEAR_WEB_ON_LOAD = false
