const GAME_LOG_TABULAR_LOOT = 'loot'
const GAME_LOG_TABULAR_SKILL = 'skill'
const GAME_LOG_TABULAR_GLOBAL = 'global'
const GAME_LOG_TABULAR_STATISTICS = 'statistics'
const GAME_LOG_TABULAR_MISSING = 'missing'
const GAME_LOG_TABULAR_RAW = 'raw'

interface GameLogState { }

export {
    GameLogState,
    GAME_LOG_TABULAR_LOOT,
    GAME_LOG_TABULAR_SKILL,
    GAME_LOG_TABULAR_GLOBAL,
    GAME_LOG_TABULAR_STATISTICS,
    GAME_LOG_TABULAR_MISSING,
    GAME_LOG_TABULAR_RAW
}
