interface SheetsState {
    pending: SheetsPending[],
    timeoutId: NodeJS.Timeout
}

interface SheetsPending {
    operationType: number,
    date: number,
    material: string,
    parameters: any[],
    doneParameters?: any[],
}

const OPERATION_TYPE_REFINED_SOLD_ACTIVE = 0
const OPERATION_TYPE_REFINED_AUCTION_MATERIAL = 1
const OPERATION_TYPE_REFINED_BUY_MATERIAL = 2
const OPERATION_TYPE_REFINED_ORDER_MATERIAL = 3
const OPERATION_TYPE_REFINED_USE_MATERIAL = 4
const OPERATION_TYPE_REFINED_REFINE_MATERIAL = 5

export {
    OPERATION_TYPE_REFINED_SOLD_ACTIVE,
    OPERATION_TYPE_REFINED_AUCTION_MATERIAL,
    OPERATION_TYPE_REFINED_BUY_MATERIAL,
    OPERATION_TYPE_REFINED_ORDER_MATERIAL,
    OPERATION_TYPE_REFINED_USE_MATERIAL,
    OPERATION_TYPE_REFINED_REFINE_MATERIAL,
    SheetsState,
    SheetsPending,
}
