import { initialState, reduceSetCurrentInventory, reduceLoadInventoryState, reduceSortAuctionBy, reduceSortAvailableBy, reduceHideByName, reduceShowByName, reduceHideByContainer, reduceShowByContainer, reduceHideByValue, reduceShowByValue, reduceShowAll, reduceShowTradingItemData, reduceAddAvailable, reduceRemoveAvailable, reduceLoadTradingItemData, reduceSortTradeOwnedBlueprintsBy, reduceSortTradeFavoriteBlueprintsBy, reduceSortTradeOtherBlueprintsBy, reduceShowHiddenItems, reduceSetOwnedOptions } from "../helpers/inventory"
import { SET_CURRENT_INVENTORY, LOAD_INVENTORY_STATE, HIDE_BY_NAME, SHOW_BY_VALUE, HIDE_BY_CONTAINER, SHOW_BY_CONTAINER, SHOW_BY_NAME, HIDE_BY_VALUE, SHOW_ALL, SORT_AUCTION_BY, ADD_AVAILABLE, REMOVE_AVAILABLE, SORT_AVAILABLE_BY,  SET_BY_STORE_ITEM_EXPANDED, SET_BY_STORE_FILTER, SET_BY_STORE_ITEM_NAME, START_BY_STORE_ITEM_NAME_EDITING, CONFIRM_BY_STORE_ITEM_NAME_EDITING, CANCEL_BY_STORE_ITEM_NAME_EDITING, SORT_BY_STORE_BY, SET_BY_STORE_ITEM_STARED, SET_BY_STORE_STARED_ITEM_EXPANDED, SET_BY_STORE_STARED_FILTER, SORT_BY_STORE_STARED_BY, START_BY_STORE_STARED_ITEM_NAME_EDITING, CONFIRM_BY_STORE_STARED_ITEM_NAME_EDITING, CANCEL_BY_STORE_STARED_ITEM_NAME_EDITING, SET_BY_STORE_STARED_ITEM_NAME, SET_BY_STORE_STARED_ITEM_STARED, SET_BY_STORE_STARED_ALL_ITEMS_EXPANDED, SET_BY_STORE_ALL_ITEMS_EXPANDED, SET_BY_STORE_MATERIAL_FILTER, SORT_BY_STORE_MATERIAL_BY, SET_BY_STORE_MATERIAL_ITEM_EXPANDED, SHOW_TRADING_ITEM_DATA, LOAD_TRADING_ITEM_DATA, SORT_TRADE_FAVORITE_BLUEPRINTS_BY, SORT_TRADE_OWNED_BLUEPRINTS_BY, SORT_TRADE_OTHER_BLUEPRINTS_BY, SHOW_HIDDEN_ITEMS, SET_OWNED_OPTIONS } from "../actions/inventory"
import { reduceCancelByStoreItemNameEditing, reduceCancelByStoreStaredItemNameEditing, reduceConfirmByStoreItemNameEditing, reduceConfirmByStoreStaredItemNameEditing, reduceSetByStoreAllItemsExpanded, reduceSetByStoreMaterialFilter, reduceSetByStoreMaterialItemExpanded, reduceSetByStoreInventoryFilter, reduceSetByStoreItemExpanded, reduceSetByStoreItemName, reduceSetByStoreItemStared, reduceSetByStoreStaredAllItemsExpanded, reduceSetByStoreStaredInventoryFilter, reduceSetByStoreStaredItemExpanded, reduceSetByStoreStaredItemName, reduceSetByStoreStaredItemStared, reduceSortByStoreBy, reduceSortByStoreMaterialBy, reduceSortByStoreStaredBy, reduceStartByStoreItemNameEditing, reduceStartByStoreStaredItemNameEditing } from "../helpers/inventory.byStore"

export default (state = initialState, action) => {
    switch (action.type) {
        case LOAD_INVENTORY_STATE: return reduceLoadInventoryState(state, action.payload.state)
        case SET_CURRENT_INVENTORY: return reduceSetCurrentInventory(state, action.payload.inventory)
        case SET_BY_STORE_ITEM_EXPANDED: return reduceSetByStoreItemExpanded(state, action.payload.id, action.payload.expanded)
        case SET_BY_STORE_ALL_ITEMS_EXPANDED: return reduceSetByStoreAllItemsExpanded(state, action.payload.expanded)
        case SET_BY_STORE_FILTER: return reduceSetByStoreInventoryFilter(state, action.payload.filter)
        case START_BY_STORE_ITEM_NAME_EDITING: return reduceStartByStoreItemNameEditing(state, action.payload.id)
        case CONFIRM_BY_STORE_ITEM_NAME_EDITING: return reduceConfirmByStoreItemNameEditing(state, action.payload.id)
        case CANCEL_BY_STORE_ITEM_NAME_EDITING: return reduceCancelByStoreItemNameEditing(state, action.payload.id)
        case SET_BY_STORE_ITEM_NAME: return reduceSetByStoreItemName(state, action.payload.id, action.payload.name)
        case SET_BY_STORE_ITEM_STARED: return reduceSetByStoreItemStared(state, action.payload.id, action.payload.stared)
        case SET_BY_STORE_STARED_ITEM_EXPANDED: return reduceSetByStoreStaredItemExpanded(state, action.payload.id, action.payload.expanded)
        case SET_BY_STORE_MATERIAL_ITEM_EXPANDED: return reduceSetByStoreMaterialItemExpanded(state, action.payload.id, action.payload.expanded)
        case SET_BY_STORE_STARED_FILTER: return reduceSetByStoreStaredInventoryFilter(state, action.payload.filter)
        case START_BY_STORE_STARED_ITEM_NAME_EDITING: return reduceStartByStoreStaredItemNameEditing(state, action.payload.id)
        case CONFIRM_BY_STORE_STARED_ITEM_NAME_EDITING: return reduceConfirmByStoreStaredItemNameEditing(state, action.payload.id)
        case CANCEL_BY_STORE_STARED_ITEM_NAME_EDITING: return reduceCancelByStoreStaredItemNameEditing(state, action.payload.id)
        case SET_BY_STORE_STARED_ITEM_NAME: return reduceSetByStoreStaredItemName(state, action.payload.id, action.payload.name)
        case SET_BY_STORE_STARED_ITEM_STARED: return reduceSetByStoreStaredItemStared(state, action.payload.id, action.payload.stared)
        case SET_BY_STORE_STARED_ALL_ITEMS_EXPANDED: return reduceSetByStoreStaredAllItemsExpanded(state, action.payload.expanded)
        case SET_BY_STORE_MATERIAL_FILTER: return reduceSetByStoreMaterialFilter(state, action.payload.filter)
        case SORT_AUCTION_BY: return reduceSortAuctionBy(state, action.payload.part)
        case SORT_BY_STORE_BY: return reduceSortByStoreBy(state, action.payload.part)
        case SORT_BY_STORE_STARED_BY: return reduceSortByStoreStaredBy(state, action.payload.part)
        case SORT_BY_STORE_MATERIAL_BY: return reduceSortByStoreMaterialBy(state, action.payload.part)
        case SORT_AVAILABLE_BY: return reduceSortAvailableBy(state, action.payload.part)
        case HIDE_BY_NAME: return reduceHideByName(state, action.payload.name)
        case SHOW_BY_NAME: return reduceShowByName(state, action.payload.name)
        case HIDE_BY_CONTAINER: return reduceHideByContainer(state, action.payload.container)
        case SHOW_BY_CONTAINER: return reduceShowByContainer(state, action.payload.container)
        case HIDE_BY_VALUE: return reduceHideByValue(state, action.payload.value)
        case SHOW_BY_VALUE: return reduceShowByValue(state, action.payload.value)
        case SHOW_HIDDEN_ITEMS: return reduceShowHiddenItems(state, action.payload.show)
        case SHOW_ALL: return reduceShowAll(state)
        case SHOW_TRADING_ITEM_DATA: return reduceShowTradingItemData(state, action.payload.name, action.payload.chainIndex)
        case LOAD_TRADING_ITEM_DATA: return reduceLoadTradingItemData(state, action.payload.craftState, action.payload.usage)
        case SORT_TRADE_FAVORITE_BLUEPRINTS_BY: return reduceSortTradeFavoriteBlueprintsBy(state, action.payload.chainIndex, action.payload.part)
        case SORT_TRADE_OWNED_BLUEPRINTS_BY: return reduceSortTradeOwnedBlueprintsBy(state, action.payload.chainIndex, action.payload.part)
        case SORT_TRADE_OTHER_BLUEPRINTS_BY: return reduceSortTradeOtherBlueprintsBy(state, action.payload.chainIndex, action.payload.part)
        case ADD_AVAILABLE: return reduceAddAvailable(state, action.payload.name)
        case REMOVE_AVAILABLE: return reduceRemoveAvailable(state, action.payload.name)
        case SET_OWNED_OPTIONS: return reduceSetOwnedOptions(state, action.payload.change)
        default: return state
    }
}
